version: "3.9"

services:
  database:
    image: postgres
    container_name: wheather_database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
